version: "3.10.8"

services:
  django:
    container_name: django
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python search_crawl_teach/manage.py runserver 0.0.0.0:8000

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - django

  worker:
    container_name: celery
    restart: always
    build:
      context: .
    command:
      - celery -A search_crawl_teach worker -B
    depends_on:
      - redis
      - django
