# Generated by Django 4.1.5 on 2023-01-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagedata",
            name="photo",
            field=models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Фото"),
        ),
        migrations.AlterField(
            model_name="modeldata",
            name="request_data",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="search.requestdata",
                verbose_name="Запрос",
            ),
        ),
    ]
